import Head from 'next/head';
import { Box, Button, Flex, Text } from '@chakra-ui/react';
import { Card, CardHeader, CardBody, CardFooter } from '@chakra-ui/react';
import { Grid, GridItem } from '@chakra-ui/react';

export default function Home() {
  const data = [
    {
      name: 'Android Development',
      type: 'Full Time',
    },
    {
      name: '.NET Development',
      type: 'Full Time',
    },
    {
      name: 'Frontend (React)',
      type: 'Full Time',
    },
    {
      name: 'Backend (Go)',
      type: 'Full Time',
    },
    {
      name: 'iOS Development',
      type: 'Full Time',
    },
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Flex
        as={'main'}
        px={16}
        alignItems={'center'}
        height={'100vh'}
        justifyContent={'center'}
        flexDir={'column'}
      >
        <Text
          color={'white'}
          fontSize={'2xl'}
          mb={8}
        >
          Select Your Domain
        </Text>
        <Grid
          templateColumns="repeat(5, 1fr)"
          gap={12}
        >
          {data.map((item) => (
            <GridItem
              key={item.name}
              w={'156px'}
              bgColor={'#252525'}
              rounded={'md'}
              height={'48'}
              p={2}
            >
              <Box
                rounded={'md'}
                bgColor={'white'}
                w={'100%'}
                height={'50%'}
                mb={2}
              ></Box>
              <Box mb={4}>
                <Text
                  fontWeight={'semibold'}
                  color={'white'}
                  fontSize={'xs'}
                >
                  {item.name}
                </Text>
                <Text
                  color={'#929292'}
                  fontSize={'xs'}
                >
                  {item.type}
                </Text>
              </Box>
              <Button
                variant={'outline'}
                color="white"
                _hover={{
                  bgColor: '#CB5FFE',
                }}
                size={'xs'}
                w={'full'}
              >
                Select
              </Button>
            </GridItem>
          ))}
        </Grid>
        <Button
          mt={12}
          variant={'solid'}
          size={'sm'}
          w={'156px'}
          _hover={{
            bgColor: '#CB5FFE',
            color: 'white',
          }}
        >
          Apply
        </Button>
      </Flex>
    </div>
  );
}
